name = "notus-app"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "notus_db"
database_id = "5b891d68-efe8-4b40-8dd8-8f3d8d4ef710"