name = "notus-app"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-03-04"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "notus_db"
database_id = "8728ed98-e71e-4501-a1e4-a1db4b150993"